### PR TITLE
Fix pcolormesh plots with cartopy

### PR DESCRIPTION
**Pull request by shoyer**
```python
proj = ccrs.Orthographic(central_longitude=230, central_latitude=5)
fig, ax = plt.subplots(figsize=(20, 8), subplot_kw=dict(projection=proj))
x.plot.pcolormesh(ax=ax, transform=ccrs.PlateCarree())
ax.coastlines()
```

Before:
image

After:
image

### CODE REVIEW

**Comment by clarkfitzg** [comment]
Works for me. And we still need to do imshow, right?

**Comment by shoyer** [comment]
I think I figured out the fix for that, will share in a bit

**Comment by shoyer** [comment]
My last commit fixes the default options for imshow with cartopy, as suggested by @kjordahl in https://github.com/xray/xray/pull/514 -- now it produces the same test image by default.

I'm not quite sure how to test these changes... I guess we should consider installing cartopy on Travis?

**Comment by clarkfitzg** [comment]
In the future we'll probably want to do more with Cartopy. So yes, it might be nice to get it going on Travis.

**Comment by clarkfitzg** [comment]
Is this ready or do you want to wait until setting up cartopy?

**Comment by shoyer** [comment]
Yeah, probably better to just merge this for now.

**Pull request merged**
