### PR TITLE
Bug when encoding datetime64 with NaT as first value

### PR DESCRIPTION
**Pull request by shoyer**
Thanks @hdail for the report

### CODE REVIEW

**Comment by jhamman** [comment]
@shoyer - this looks good... Although, what's up with the branch name `datetime65`?

**Comment by kjordahl** [comment]
@jhamman 

It's one louder

**Comment by shoyer** [comment]
Merging this....

I have no idea where datetime65 came from :)

**Comment by jhamman** [comment]
:thumbsup:

**Pull request merged**
