### PR TITLE
Fix pickle on DataArray objects

### LINKED ISSUE #515: pickle hits recursion limit while loading a xray.DataArray
Hi,

The following code raises `RuntimeError` in pickle:

```python
import pickle
import xray
import numpy

signal = xray.DataArray(numpy.random.random((3,3)), dims=('id', 'time'))

with open('signal.pickle', 'w') as signal_file:
    pickle.dump(signal, signal_file)

with open('signal.pickle') as signal_file:
    signal = pickle.load(signal_file)
```

The backtrace is following (I shortened it but I think you'll get the point):

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-2d6533ac9fa3> in <module>()
      8 
      9 with open('signal.pickle') as signal_file:
---> 10     signal = pickle.load(signal_file)

/usr/lib/python2.7/pickle.pyc in load(file)
   1376 
   1377 def load(file):
-> 1378     return Unpickler(file).load()
   1379 
   1380 def loads(str):

/usr/lib/python2.7/pickle.pyc in load(self)
    856             while 1:
    857                 key = read(1)
--> 858                 dispatch[key](self)
    859         except _Stop, stopinst:
    860             return stopinst.value

/usr/lib/python2.7/pickle.pyc in load_build(self)
   1213         state = stack.pop()
   1214         inst = stack[-1]
-> 1215         setstate = getattr(inst, "__setstate__", None)
   1216         if setstate:
   1217             setstate(state)

/usr/local/lib/python2.7/dist-packages/xray/core/common.pyc in __getattr__(self, name)
    128 
    129     def __getattr__(self, name):
--> 130         for source in self.__attr_sources__:
    131             try:
    132                 return source[name]

/usr/local/lib/python2.7/dist-packages/xray/core/dataarray.pyc in __attr_sources__(self)
    383     def __attr_sources__(self):
    384         """List of places to look-up items for attribute-style access"""
--> 385         return [self.coords, self.attrs]
    386 
    387     def __contains__(self, key):

/usr/local/lib/python2.7/dist-packages/xray/core/dataarray.pyc in coords(self)
    423         """Dictionary-like container of coordinate arrays.
    424         """
--> 425         return DataArrayCoordinates(self)
    426 
    427     def reset_coords(self, names=None, drop=False, inplace=False):

/usr/local/lib/python2.7/dist-packages/xray/core/coordinates.pyc in __init__(self, dataarray)
    181     def __init__(self, dataarray):
    182         self._dataarray = dataarray
--> 183         self._dataset = dataarray._dataset
    184 
    185     def update(self, other):

/usr/local/lib/python2.7/dist-packages/xray/core/common.pyc in __getattr__(self, name)
    128 
    129     def __getattr__(self, name):
--> 130         for source in self.__attr_sources__:
    131             try:
    132                 return source[name]

/usr/local/lib/python2.7/dist-packages/xray/core/dataarray.pyc in __attr_sources__(self)
    383     def __attr_sources__(self):
    384         """List of places to look-up items for attribute-style access"""
--> 385         return [self.coords, self.attrs]
    386 
    387     def __contains__(self, key):

/usr/local/lib/python2.7/dist-packages/xray/core/dataarray.pyc in coords(self)
    423         """Dictionary-like container of coordinate arrays.
    424         """
--> 425         return DataArrayCoordinates(self)
    426 
    427     def reset_coords(self, names=None, drop=False, inplace=False):

/usr/local/lib/python2.7/dist-packages/xray/core/coordinates.pyc in __init__(self, dataarray)
    181     def __init__(self, dataarray):
    182         self._dataarray = dataarray
--> 183         self._dataset = dataarray._dataset
    184 
    185     def update(self, other):

...
: maximum recursion depth exceeded while calling a Python object
```

### PR DESCRIPTION
**Pull request by shoyer**
Fixes #515

### CODE REVIEW

**Comment by shoyer** [comment]
This actually works now, if anyone wants to give this a review

**Comment by jhamman** [comment]
This looks pretty good to me.  Can you explain why  we need the `_initialized` attribute?

**Comment by shoyer** [comment]
OK, new approach, now that I finally understand what is going on. Got ride of `_initialized`, put an explicit check for `__setstate__` in `__getattr__`.

**Comment by jhamman** [comment]
This looks good to me.  Much cleaner than before.

**Pull request merged**
