### PR TITLE
build local docs using matplotlib Agg backend

### PR DESCRIPTION
**Pull request by clarkfitzg**
Addresses discussion in #509.

### CODE REVIEW

**Comment by jhamman** [comment]
I just tested this locally and it works.  Got to love the one line fixes. Once all the tests pass, I think you can merge this.

**Comment by clarkfitzg** [comment]
Explanation-

Looks like the backend is set when Seaborn is imported. When building the docs we don't want to use an interactive [backend](http://matplotlib.org/faq/usage_faq.html#what-is-a-backend).

```
(xray_dev)testimage ~/dev/xray/doc $ ipython
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:04:42)

...

In [1]: import seaborn

In [2]: import matplotlib

In [3]: matplotlib.use('Agg')
/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/matplotlib/__init__.py:1318: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
```

**Comment by jhamman** [comment]
nice. maybe raise an issue over at seaborn?  I think they try to (should) have round trip zero net change to the matplotlib namespace if you do these  two commands: 

```python
import seaborn
seaborn.reset_orig()
```

But since the backend can't be set twice, this doesn't work.

**Comment by clarkfitzg** [comment]
Yes, this is a little tricky. Internally Seaborn uses lots of `pyplot`. And importing `pyplot` sets the backend. So maybe they could try something like [pyplot.switch_backend](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.switch_backend) within their `reset_orig` function?

**Comment by clarkfitzg** [comment]
But really if people need to use a particular backend (like in our case) they should be setting it in the first place. Seaborn doesn't go beyond what `pyplot` does here, so I think it's ok.

**Comment by clarkfitzg** [comment]
```
In [1]: import matplotlib

In [2]: import matplotlib.pyplot

In [3]: matplotlib.use('Agg')
/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/matplotlib/__init__.py:1318: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
```

**Pull request merged**
