### PR TITLE
Preprocess argument for open_mfdataset and threading lock

### LINKED ISSUE #443: multiple files - variable X not equal across datasets
The other day I was playing with `xray.open_mfdataset` and I noticed you can get this error, when opening multiple files at the same time. I think there is a pretty easy solution to this:

```python
import glob as g
from toolz.curried import curry, map, pipe
import xray

def get_ds(glob):
    def _get_ds(file_path):
        dim = 'mean_height_agl'
        dim_new = 'agl'
        with xray.open_dataset(file_path) as _ds:
            _ds.load()
            return (_ds.assign_coords(**{dim_new:
                                         (dim, range(_ds.coords[dim].size))})
                    .swap_dims({dim: dim_new}))

    return pipe(g.glob(glob),
                sorted,
                map(_get_ds),
                curry(xray.concat)(dim='time'))
```

Of course, this is for a particular variable I was having trouble with, but the idea is to swap dimensions, that is create a dummy dimension with the same length as the troublesome variable and then swap the two. This can be done for any number of troublesome variables. I don't know how feasible this is though. Just thought to share my idea...

### LINKED ISSUE #444: segmentation fault with `open_mfdataset`
This is super strange. Does anyone have any idea why a segmentation fault might be happening here?

```
Python 3.4.3 (default, Jun 26 2015, 00:02:21) 
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xray
>>> xray.open_mfdataset('2*.nc', concat_dim='time')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ichec/home/users/razvan/.local/lib/python3.4/site-packages/xray/backends/api.py", line 205, in open_mfdataset
Segmentation fault (core dumped)
```

I stay it's strange because I ended up tracking down the bug to `xray.core.ops.array_equiv`. I have no idea what's going on, but by mistake I found out that if I introduce `isnull(arr1 & arr2)` just before the `return` statement then I don't get the error any more... So my `xray.core.ops.array_equiv` is now:

```
def array_equiv(arr1, arr2):
    """Like np.array_equal, but also allows values to be NaN in both arrays
    """
    arr1, arr2 = as_like_arrays(arr1, arr2)
    if arr1.shape != arr2.shape:
        return False
    # segmentation fault if we don't call this here...
    isnull(arr1 & arr2)
    return bool(((arr1 == arr2) | (isnull(arr1) & isnull(arr2))).all())
```
Thanks...

### PR DESCRIPTION
**Pull request by shoyer**
Fixes #443
Fixes #444

### CODE REVIEW

**Comment by shoyer** [comment]
Going to merge this shortly, unless anyone has a better name for `preprocess`

**Comment by razvanc87** [comment]
I have a question about this preprocess thing. Would it mean now that... basically `xray` will  load all data in memory? because of the preprocesing step, whereas before... or at least that's what I understood from the documentation, `xray` would access the data by a need only basis.

**Comment by shoyer** [comment]
Nope, each dataset is loaded lazily when using `open_mfdataset` (via [dask](http://dask.pydata.org/)). As long as you stick to xray operations and don't actually manually load data into memory (e.g., by calling `.load()`) the data is only accessed and transformed by `preprocess` on a need only basis.

**Comment by razvanc87** [comment]
I need to get my head around this... I know that when you do list comprehension, this isn't lazy so basically it goes through the loop and evaluates for each iteration... so I thought that:
```
    if preprocess is not None:
        datasets = [preprocess(ds) for ds in datasets]
```
translates to forcing the application of the `preprocess` function to the dataset effectively loading it in memory... anyway, this is really cool, I'll definitely try it out :+1:

**Pull request merged**
