### PR TITLE
cast DataArray name to string if not None

### LINKED ISSUE #533: DataArray.name should always be a string
Consider the following example:

```Python
import numpy as np
import xray

da = xray.DataArray(np.random.random((4, 5)))
ds = da.to_dataset(name=0) # or name=True, or name=(4)
ds.to_netcdf('test.nc')
```
raises this error:
```python
/Users/jhamman/anaconda/lib/python3.4/site-packages/xray/backends/netCDF4_.py in prepare_variable(self, name, variable)
    228             endian='native',
    229             least_significant_digit=encoding.get('least_significant_digit'),
--> 230             fill_value=fill_value)
    231         nc4_var.set_auto_maskandscale(False)
    232 

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.createVariable (netCDF4/_netCDF4.c:13217)()

/Users/jhamman/anaconda/lib/python3.4/posixpath.py in normpath(path)
    330     if path == empty:
    331         return dot
--> 332     initial_slashes = path.startswith(sep)
    333     # POSIX allows one or two initial slashes, but treats three or more
    334     # as single slash.

AttributeError: 'int' object has no attribute 'startswith'
```

I think one way to solve this is to cast the name attribute to a string at the time of assignment.  Another way is just to raise an error if a not string variable name is used.

### PR DESCRIPTION
**Pull request by jhamman**
closes #533

### CODE REVIEW

**Comment by clarkfitzg** [comment]
You mentioned in the bug report:

> Another way is just to raise an error if a not string variable name is used.

Raising a `TypeError` seems like the way to go here, since `str` works on anything. Relevant line in 'Zen':

> In the face of ambiguity, refuse the temptation to guess.

Also, are there other places to implement this? Say the keys of a `dataset`?

**Comment by jhamman** [comment]
I'm happy to raise an error instead.  I may have misunderstood @shoyer's comment in #533.

**Comment by shoyer** [comment]
Indeed, I think it's better to raise than silently convert -- that's much more Pythonic.

The keys of a dataset would be the other place to enforce this.

Maybe the only place to silently convert is in the `to_dataset` method of DataArray, when splitting an existing dimension to create a dataset with new variables? Otherwise that method is not guaranteed to succeed, which seems like a Bad Thing.

**Comment by jhamman** [comment]
@shoyer - 

>Maybe the only place to silently convert is in the to_dataset method of DataArray, when splitting an existing dimension to create a dataset with new variables? Otherwise that method is not guaranteed to succeed, which seems like a Bad Thing.

If you are splitting a dataset along a dimension, we don't use the `name` argument: https://github.com/xray/xray/blob/master/xray/core/dataarray.py#L243-L273. So I don't think any changes are needed in that case.  In fact, in `_to_dataset_split()`, the labels are cast to strings.

I'm going to close this PR and open a new one with errors raised instead of silently converting.

**Pull request closed without merging**
