### PR TITLE
update monthly-means.rst using example data from xray-data repo

### LINKED ISSUE #424: include data for 'Calculating Seasonal Averages ... ' Example
The example [Calculating Seasonal Averages ... ](https://github.com/xray/xray/blob/master/doc/examples/monthly-means.rst) is apparently impossible to replicate without access to the datafile ```R1002RBRxaaa01a.vic.hmm.197909-201212.nc```. A google search does not find such a file, nor does it appear to be in the xray repo. The example is considerably less useful if the novice cannot 'follow along at home'.  (I realize that sharing the data may require some legal gymnastics; perhaps a simpler example--with faked data, say--would suffice.)

### PR DESCRIPTION
**Pull request by jhamman**
fixes #424 

related: https://github.com/xray/xray-data/pull/1

### CODE REVIEW

**Comment by shoyer** [comment]
Maybe you could also check in your notebook (e.g., to an `examples` directory), so users could directly open it up and around with it?

I would suggest making this example run automatically, but we can't do netCDF4 yet on ReadTheDocs (sigh).

BTW -- if you add your `hydro.washington.edu` email to your GitHub account, then your contributions to xray would appear on the Contributors page :).

**Comment by jhamman** [comment]
Okay, were you thinking of an examples directory in `xray` or `xray-data`?

Also, my email recently changed so I'll update that in my `gitconfig` and on *github* which should update my contributor status.

**Comment by shoyer** [comment]
You can put the examples directory in xray.

**Comment by shoyer** [comment]
once we merge #474, add a link to the notebook on this docs page?

**Comment by jhamman** [comment]
added the line in 3f9b5d4.

**Comment by shoyer** [comment]
again, thanks!

**Pull request merged**
